### ISSUE TITLE
Sennheiser eW 100/300/500 G3 A-Band

### ISSUE THREAD

**Issue by elraval** [berkon/wireless-microphone-analyzer#1]
Here's a new table, same format as the ones found at:

wireless-microphone-analyser-master>frequency_data>presets

Data extracted from:

https://assets.sennheiser.com/global-downloads/file/11015/Overview_Radio_Mic_Frequency_charts_2014.pdf

[SEN_A_G3.json.txt](https://github.com/berkon/wireless-microphone-analyzer/files/2818676/SEN_A_G3.json.txt)

**Comment by berkon** [comment]
Thanks @elraval! That's a good overview!

**Comment by berkon** [comment]
And thanks for providing the channel presets for the Sennheiser A Band (G3 Series). I've just put it in the code. Will be there with the next release. :-)

**Comment by elraval** [comment]
Cool.

If I want to keep doing this and sending them here, should I just open new issues?

I'm asking because I have litte idea about github etiquete...  Issues, pull requests, that kind of thing.

Thanks,

**Comment by berkon** [comment]
Good question. I think they don't have some kind of "comment" area here on GitHub, so I just opened this new issue:

https://github.com/berkon/wireless-microphone-analyzer/issues/2

which I'll never close, so that everybody can contribute frequency/vendor related data there.
