### ISSUE TITLE
MacOS X version - missing "Quit" Menu command, menus in wrong places.

### ISSUE THREAD

**Issue by xfade551** [berkon/wireless-microphone-analyzer#11]
Under MacOS X Catalina ("10.15"; possibly other versions, too), the "Quit" command is missing from the [Application Name] menu; also, the usual Command-Q keyboard shortcut also does not work for this, so the only option is to force-quit the application.

Unusually, the [Application Name] menu is displaying the manufacturer list; one would normally expect a separate menu named "Manufacturer" (or something along those lines). I'm just guessing, but this issue might just be a result of an off-by-one error in the menu numbering for MacOS X. (The usual MacOS X menu order is [Apple icon], [Application Name], File, Edit, then the software-specific menus.)

**Comment by berkon** [comment]
Thanks for your hint @xfade551. I must admit that I'm a very basic Mac user. ;-) I only use it for DJ-ing. Thus I'm not fully aware of the guidelines which apps should follow on Mac. Its embarrassing, but I thought right clicking "Quit" on the app in the taskbar would be the normal way to terminate an app on the Mac. ;-) But yes, you are correct! The issue with the vendor bands being displayed in the app's menu is Mac specific. On Windows the vendor bands are listed in a menu called "Bands" (as someone would expect). Don't know why the Mac is simply ignoring this entry. I'll check/correct this.

**Comment by berkon** [comment]
Fixed in version V1.7.3 (see commit https://github.com/berkon/wireless-microphone-analyzer/commit/f782fa40cfc901c1645b1c1469d5d230e891e757)
