### ISSUE TITLE
Compatability with IoT module

### ISSUE THREAD

**Issue by JonnyTech** [berkon/wireless-microphone-analyzer#20]
What is needed to make this software compatible with the RF Explorer IoT module (https://j3.rf-explorer.com/60-rfe/specifications/182-rf-explorer-3g-iot-for-raspberry-pi)? It currently does not detect the hardware, regardless of changing baud rates.

**Comment by berkon** [comment]
@JonnyTech, unfortunately I do not have such a hardware to test with. Thus, I can't tell what changes are required. I think you have to contact the manufacturer in order to get more information. Then maybe I can find a way to implement it and let someone else do the testing.

**Comment by JonnyTech** [comment]
Shall create a PR if I do get it working. Thanks.

**Comment by berkon** [comment]
Sure, of course. I really appreciate your help!
