### ISSUE TITLE
Java Script Error

### ISSUE THREAD

**Issue by NorbenSG** [berkon/wireless-microphone-analyzer#29]
Started the Programm once it worked fine, after a while it crashed and is showing a java script error when iam selecting a frequenzy band. Not showing any rf explorer signal at all.

**Comment by berkon** [comment]
Please post the error message, thanks.

**Comment by NorbenSG** [comment]
![tbFvChQLQZOOEL4HbHqs6g](https://user-images.githubusercontent.com/119695528/205366199-eed1a505-b039-4002-a152-b9327ce03f51.jpg)
![POKfCNXwTwCx4MnFW4bqZw](https://user-images.githubusercontent.com/119695528/205366259-bd118110-cbb2-40d7-be00-5b2e7adb74c8.jpg)

**Comment by tiganov** [comment]
@berkon Any update on this? I am also getting this issue and it makes the tool often unusable. I have to restart and scroll in and out for it to work (and I must do this multiple times until it works). I’m on macOS.

**Comment by berkon** [comment]
Closing stale issue.
