### ISSUE TITLE
saving tracings

### ISSUE THREAD

**Issue by nerdymedic** [berkon/wireless-microphone-analyzer#3]
It would be incredibly helpful to automate sweeping across a range and savings the amplitude tracing so it can be imported into RF coordination software like IAS

**Comment by berkon** [comment]
Can you send an example file, so that I can see how the format must look like? I read that IAS can import CSV as well. That would be the easiest way I guess.

**Comment by nerdymedic** [comment]
[RFExplorer_SingleSweepData_2014_09_02_11_01_22.txt](https://github.com/berkon/wireless-microphone-analyzer/files/2922584/RFExplorer_SingleSweepData_2014_09_02_11_01_22.txt)

**Comment by berkon** [comment]
Looks like the format is the same like for WW6. I've just released a new version (V 1.3.0) which supports WW6 export. So I guess the exported CSV file should work in IAS as well. If yes, I'll change the name of the menu item correspondingly in the next release to reflect that IAS export is supported as well.

**Comment by nerdymedic** [comment]
Tried it, IAS will not read it. Comparing it to a file that it will import, I can't see any difference. I'll email IAS's dev and try to get some answers.

**Comment by berkon** [comment]
I just downloaded a trial version of IAS and imported the CSV. Seems to work without issues:

![image](https://user-images.githubusercontent.com/28842661/53700719-9d7ce280-3df5-11e9-8e73-433a3dbdb702.png)

**Comment by scriptwarlock** [comment]
good day boss bernd, is it redundant to put another set of menu inside the
'about and docuentation'

**Comment by berkon** [comment]
I added the Help submenu because on Mac its not possible to directly click a toplevel menu without a submenu.

**Comment by scriptwarlock** [comment]
ok got it

**Comment by nerdymedic** [comment]
This may be some sort of artefact in the way the mac vs other versions behave. The mac version included quotes around the freqs on export:
"537.6","-87.5"
"538.285","-89.5"
"538.971","-88.5"

Remove the quotes and it behaves as expected - ie imports successfully.

**Comment by berkon** [comment]
That‘s a really good hint, thanks! Indeed it looks like the Mac behaves differently at that point. I‘ll check...

**Comment by berkon** [comment]
I can't confirm this issue on my Mac. The exported file looks exactly the same like on my PC.

**Comment by nerdymedic** [comment]
I'm on os 10.14.3, what about you?

**Comment by nerdymedic** [comment]
Can confirm the current version export the file correctly. Still unable to import, but this is  likely something specific to my version of IAS/parallels/MacOS.

**Comment by berkon** [comment]
I'm still on Sierra (10.12).
