### ISSUE TITLE
Scan Resolution

### ISSUE THREAD

**Issue by BernatVM** [berkon/wireless-microphone-analyzer#33]
I find myself very limited with the resolution on the scann. I work as a sound tech, coordinating systems with 20+ RF channels and the csv export for WWB6 has not enough resolutino for me to make decissions over which frecuencies to use.

**Comment by berkon** [comment]
The resolution is a limitation given by the hardware. If you need a higher resolution you probably have to look for (much) more expensive hardware/software solutions.

**Comment by arocholl** [comment]
Actually working with PLUS models, you can have resolution you need, up to 65.000 data points. It is only a matter of the software to use the High Resolution mode from the API.

**Comment by BernatVM** [comment]
I'm no expert but using TouchstonePRO with the same hardware I get the scans my usign right now. I don't want to sound arrogant, is juts english not my mother tongue. I think this software is great and also very annoyed about the need to buy propietary software for using a tool that I already bought and paid for. This is a great tool.

**Comment by arocholl** [comment]
Touchstone PRO does multiple step small scans to overcome the limitation of simpler models, it is a good trick but scan is slow.

**Comment by berkon** [comment]
No problem @BernatVM your welcome. ;-) Thanks for the information @arocholl, I must admit I didn't know that newer models have a higher number of data points. Unfortunately I don't have such a device. I only have the old RF Explorer 3 hardware. So I can't adapt / test the software for it. I'm not part of the company which builds/sells these devices. This is just an open source project which I started on my own.
