### ISSUE TITLE
Can you add support for tinySA?

### ISSUE THREAD

**Issue by hugen79** [berkon/wireless-microphone-analyzer#34]
If possible, we can send you tinySA for testing.

**Comment by berkon** [comment]
@hugen79, thanks for your request. As this tool was initially developed for the RFExplorer hardware, it is very specific in regards to the serial protocol. So I think the major question regarding TinySA is, if the way to access the scan data and control the device is somehow similar. Do you have some detailed documentation especially how to set the frequency, the span, scan points and how the scan data is then sent from the device?

**Comment by hugen79** [comment]
Hello berkon, thank you very much for your reply, the data format of [tinySA ](https://github.com/erikkaashoek/tinySA)is very simple and clear, this page provides a list of commands for tinySA, you can always contact  @erikkaashoek , the developer of tinySA, if you need help.
https://tinysa.org/wiki/pmwiki.php?n=Main.USBInterface

**Comment by berkon** [comment]
Hello @hugen79, sounds interesting. So if it is possible to send a device, that would be great. I can't promise a date when it will be finished, because I'm very busy at the moment, but I will surely start asap. Can you give me your email address so that I can send the shipping address? If you don't want to disclose it, just send an email to me (bernd@konnerth.de), then I'll reply with my shipping address. Thanks a lot in advance!

**Comment by Madddcow** [comment]
I have an RF Explorer and am waiting on a tinySA Ultra to be delivered.  Has there been any progress with this situation i.e. did hugen79 send a tinySA for testing? I'd be very keen to use Wireless Microphone Analyzer with the tinySA

**Comment by berkon** [comment]
@Madddcow, yes I'm already working on the implementation and I have the devices available. But currently I'm very busy. I hope I can continue work on this project in about two month.

**Comment by berkon** [comment]
Good news! I'm nearly done with the implementation. I hope I can release a new version within the next days. So stay tuned. ;-)

**Comment by Madddcow** [comment]
@berkon, I'm excited to hear this!  Looking forward to trying it out!!  Thank you :)

**Comment by berkon** [comment]
V2.0.0 with TinySA support is now available.
