### ISSUE TITLE
Software blank screen

### ISSUE THREAD

**Issue by rjurden** [berkon/wireless-microphone-analyzer#36]
I am running the software on a Macbook Pro M3 Pro and MacOS 14.1

When the software opens, after a few seconds, it resets the RF Explorer's scan range to 240.000 - 240.000 and won't allow me to change it using the menus.

Eventually, the screen goes white.

I have tried to re-install the software, and that didn't solve the issue.

Any advice is appreciated :)

**Comment by berkon** [comment]
@rjurden, unfortunately I'm currently very busy so I cannot debug your issue. What you can try is to remove the configuration file of the app and restart it afterwards. Go to your home directory and then to:

`.config/configstore` there you should find a file called `wireless-microphone-analyzer.json`.

Remove it and restart the app. It will be recreated at startup. Maybe something went wrong there ...

**Comment by berkon** [comment]
The next release of the tool will contain a menu option to remove the configuration file in case it gets screwed up for some reason.
