### ISSUE TITLE
Please provide an AppImage for download

### ISSUE THREAD

**Issue by probonopd** [berkon/wireless-microphone-analyzer#4]
https://github.com/berkon/wireless-microphone-analyzer/blob/4c230a01bca215e084a236d8c1cbda90dcbe034e/package.json#L45

Please provide an AppImage for download on GitHub Releases, thank you.

**Comment by berkon** [comment]
There you go ...

> [wireless-microphone-analyzer/package.json](https://github.com/berkon/wireless-microphone-analyzer/blob/4c230a01bca215e084a236d8c1cbda90dcbe034e/package.json#L45)
> 
> Line 45 in [4c230a0](/berkon/wireless-microphone-analyzer/commit/4c230a01bca215e084a236d8c1cbda90dcbe034e)
> 
>  "AppImage", 
> Please provide an AppImage for download on GitHub Releases, thank you.
