### ISSUE TITLE
Can't export to wwb6 or 7

### ISSUE THREAD

**Issue by EMLGVS** [berkon/wireless-microphone-analyzer#40]
Seems file can't be read when trying to be imported to shure workbench 

<img width="423" alt="Screenshot 2024-01-16 at 00 30 37" src="https://github.com/berkon/wireless-microphone-analyzer/assets/156743846/c0478b39-03fb-48fc-be0a-154eb93d7cb6">

**Comment by berkon** [comment]
Did you choose a frequency range which is valid for Shure microphones? According to the error message, it looks like that range is wrong. If the range is correct, please send me the exported file and I will have a look.

**Comment by EMLGVS** [comment]
Yes I have chosen the right range.

I found that the frequencies that are labeled in the CSV file are wrong.
Same as the way they appear in the program.
(On OSX)

Frequencies are labeled 500.250.000
On all capture points  the last .000 is not needed.

I have compared a CSV file from vantage and yours.
Try deleting the last .000 on some data. And it works in wwb

**Comment by berkon** [comment]
I've just released V2.0.2 which should fix the issue.
